language: go
deploy:
  provider: releases
  api_key:
    secure: Ijm94GPoCCXo/1qfZmKpCsliTBxQ67t0VH35G5LrfGEIcXErJpvnCg9JHrvXPuk5F8IIuacpiYN1WSFgUlR9wCw2MAPehIkwkzx7hXZ/H7L1rGZuW1TMWJU5p6KuzAImuqqQl0hG4KLZrTkTgu5qgnRlfq1soWvdgKgYMDfBCoUwxnw74i3ziEau9hLtB/xYJiizCPLhQ5hIxmqUzffrksgTlUnW5VFgKCCGJCUTrkvNYxJ7kfX48Wr6xOjCbXBSIq1AIUSLl/9n1ML1mfwXY4GTmaWY5QUvwMR9XxGQHYOJ7KRRMCwgiC9hIqjCV85Yl2VqeaXRppMvLgTR6K07BfWekt9695YGsgWbPgZXEuqVVGZJO9TtHfKqajryEJ+I3eM6d+FQw13GASat1LDEaXXo8gU6Q2gD62YFnaJFpO4porQvNT77k2KqJqUGp/fmpzNVpqASkpS5uFV5R1jdn83LHR1MBoTVRqLCt9E4eh0W6ovScH6ZPOdIFHln05UxP0hb9kCZqGogLYHQ7t9yGQYEX4k7sGAUjO0P/shvb1yzk5El7gk89Cr9Tdq+c+7QC0XXEb/7S/rRbwhebC9XWQB4Yiv1GWxiH1LH/pwhwf1daZHWfg3maGDNMeS1IauvJcYSWSGhOn5jLwlmL4mPqqRGTOs15KH8n9q166Dr5dg=
  file: ".travis.yml"
  on:
    repo: servak/teets
